/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gudenau_jgecko_natives_Linux */

#ifndef _Included_net_gudenau_jgecko_natives_Linux
#define _Included_net_gudenau_jgecko_natives_Linux
#ifdef __cplusplus
extern "C" {
#endif
#undef net_gudenau_jgecko_natives_Linux_F_SETFL
#define net_gudenau_jgecko_natives_Linux_F_SETFL 4L
#undef net_gudenau_jgecko_natives_Linux_CRTSCTS
#define net_gudenau_jgecko_natives_Linux_CRTSCTS -2147483648L
#undef net_gudenau_jgecko_natives_Linux_CS8
#define net_gudenau_jgecko_natives_Linux_CS8 48L
#undef net_gudenau_jgecko_natives_Linux_CLOCAL
#define net_gudenau_jgecko_natives_Linux_CLOCAL 2048L
#undef net_gudenau_jgecko_natives_Linux_CREAD
#define net_gudenau_jgecko_natives_Linux_CREAD 128L
#undef net_gudenau_jgecko_natives_Linux_TCSANOW
#define net_gudenau_jgecko_natives_Linux_TCSANOW 0L
#undef net_gudenau_jgecko_natives_Linux_TCIOFLUSH
#define net_gudenau_jgecko_natives_Linux_TCIOFLUSH 2L
/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    doGetRealFD
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_doGetRealFD
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    getBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_jgecko_natives_Linux_getBufferAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    getTermiosSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_getTermiosSize
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    fcntl
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_fcntl
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    tcgetattr
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_tcgetattr
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    cfmakeraw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_gudenau_jgecko_natives_Linux_cfmakeraw
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    tcsetattr
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_tcsetattr
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    tcflush
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_tcflush
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gudenau_jgecko_natives_Linux
 * Method:    compress2
 * Signature: (JJJJI)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Linux_compress2
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
