/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gudenau_jgecko_natives_Windows */

#ifndef _Included_net_gudenau_jgecko_natives_Windows
#define _Included_net_gudenau_jgecko_natives_Windows
#ifdef __cplusplus
extern "C" {
#endif
#undef net_gudenau_jgecko_natives_Windows_MAXDWORD
#define net_gudenau_jgecko_natives_Windows_MAXDWORD -1L
#undef net_gudenau_jgecko_natives_Windows_PURGE_TXABORT
#define net_gudenau_jgecko_natives_Windows_PURGE_TXABORT 1L
#undef net_gudenau_jgecko_natives_Windows_PURGE_RXABORT
#define net_gudenau_jgecko_natives_Windows_PURGE_RXABORT 2L
#undef net_gudenau_jgecko_natives_Windows_PURGE_TXCLEAR
#define net_gudenau_jgecko_natives_Windows_PURGE_TXCLEAR 4L
#undef net_gudenau_jgecko_natives_Windows_PURGE_RXCLEAR
#define net_gudenau_jgecko_natives_Windows_PURGE_RXCLEAR 8L
#undef net_gudenau_jgecko_natives_Windows_GENERIC_READ
#define net_gudenau_jgecko_natives_Windows_GENERIC_READ -2147483648L
#undef net_gudenau_jgecko_natives_Windows_GENERIC_WRITE
#define net_gudenau_jgecko_natives_Windows_GENERIC_WRITE 1073741824L
#undef net_gudenau_jgecko_natives_Windows_OPEN_EXISTING
#define net_gudenau_jgecko_natives_Windows_OPEN_EXISTING 3L
#undef net_gudenau_jgecko_natives_Windows_FILE_ATTRIBUTE_NORMAL
#define net_gudenau_jgecko_natives_Windows_FILE_ATTRIBUTE_NORMAL 128L
/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    listSerialDevices
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_gudenau_jgecko_natives_Windows_listSerialDevices
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    doCreateFile
 * Signature: (Ljava/lang/String;IIJIIJ)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_jgecko_natives_Windows_doCreateFile
  (JNIEnv *, jclass, jstring, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    doCloseHandle
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_doCloseHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    getBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_net_gudenau_jgecko_natives_Windows_getBufferAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    getCOMMTIMEOUTSSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Windows_getCOMMTIMEOUTSSize
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    GetCommTimeouts
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_GetCommTimeouts
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    SetCommTimeouts
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_SetCommTimeouts
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    SetCommMask
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_SetCommMask
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    PurgeComm
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_PurgeComm
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Windows_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    ReadFile
 * Signature: (JJI[IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_ReadFile
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    WriteFile
 * Signature: (JJI[IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gudenau_jgecko_natives_Windows_WriteFile
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray, jlong);

/*
 * Class:     net_gudenau_jgecko_natives_Windows
 * Method:    compress2
 * Signature: (JJJII)I
 */
JNIEXPORT jint JNICALL Java_net_gudenau_jgecko_natives_Windows_compress2
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
